name: Publish to NPM via Token

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

env:
  NODE_VERSION: 20
  
permissions:
  contents: read # Chỉ cần quyền đọc
  
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    
    # Định nghĩa môi trường 'npm'
    environment: npm
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      # 1. Cấu hình môi trường Node.js và NPM Registry
      - name: Setup Node.js & Configure Registry
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
          # Tự động cấu hình file .npmrc bằng token từ Secret
          node-auth-token: ${{ secrets.SECRET_TOKEN }}

      # 2. Cài đặt dependency sạch sẽ và ổn định
      - name: Clean Install Dependencies (npm ci)
        run: npm ci

      # 4. Publish gói NPM
      - name: Publish to NPM
        # Lệnh publish cơ bản, token đã được cấu hình từ bước 1
        run: npm publish 
